Workflow
jonaslod/social-media-client pull request #3
Opened 2023-01-19 10:52 UTC by jonaslod

2023-01-19 11:04 UTC, jonaslod commented
Requests review.

2023-01-23 06:51 UTC, Fermain requested changes
This is very good work, although there is one file missing. A static pages deploy with `npm build` is the unmet requirement.

2023-01-23 08:38 UTC, Fermain approved these changes

2023-01-27 11:21 UTC, Fermain approved these changes
This is a good submission without any major issues or concerns regarding the assessment criteria. Your cypress and jest tests show some lateral thinking and an understanding of the principles of this difficult subject. Enjoy your weekend!

2023-01-27 11:21 UTC, Fermain commented on src/js/api/auth/login.test.js
> +    expect(token).not.toBeNull();
You could `expect(fetch).toHaveBeenCalledTimes(1)` to harden this

2023-01-27 11:21 UTC, Fermain commented on src/js/api/posts/create.test.js
> +    expect(post).toMatchObject(mockObject);
Same here `expect(fetch).toHaveBeenCalledTimes(1)`

2023-01-27 11:32 UTC, jonaslod commented on src/js/api/auth/login.test.js
> +    expect(token).not.toBeNull();
This has now been implemented.

2023-01-27 11:32 UTC, jonaslod commented on src/js/api/posts/create.test.js
> +    expect(post).toMatchObject(mockObject);
This has now been implemented.

2023-02-14 09:18 UTC, Fermain approved these changes
A good submission that shows confidence with workflow tooling.

2023-02-14 09:18 UTC, merged